#!/usr/bin/python
import subprocess, sys

if sys.argv[1]=='brightness':
    current_value = str(subprocess.check_output('brightnessctl get', shell=True))
    current_value = ''.join(filter(str.isdigit, current_value))
    percent = ( int(current_value) / 234 * 100 )
    print(int(percent))
elif sys.argv[1]=='audio':
    percent = str(subprocess.check_output('pamixer --get-volume-human', shell=True))
    percent = ''.join(filter(str.isdigit, percent))
    print(int(percent))

